export default {
  res1: {
    id: 'res1',
    src: 'mac.jpg',
    alt: 'Макдоналдс',
    name: 'Макдоналдс — Газетный',
    desc: ' • Бургеры',
    time: '25 - 35 Min',
    menu: [1, 2, 3, 4, 5, 6],
  },
  res2: {
    id: 'res2',
    src: 'dimsum.jpg',
    alt: 'DimSum & Co',
    name: 'DimSum & Co — ЦДМ',
    desc: ' • Японская • Китайская • Азиатская',
    time: '40 - 50 Min',
    menu: [7, 8, 9, 10, 11, 12],
  },
  res3: {
    id: 'res3',
    src: 'dvijok.jpg',
    alt: 'ДвижОК',
    name: 'ДвижОК — Манежная',
    desc: ' • Американская • Европейская',
    time: '35 - 45 Min',
    menu: [13, 14, 15, 16, 17, 18],
  },
  res4: {
    id: 'res4',
    src: 'pizzalove.jpg',
    alt: 'PIZZELOVE',
    name: 'PIZZELOVE',
    desc: ' • Пицца',
    time: '15 - 25 Min',
    menu: [19, 20, 21, 22, 23, 24],
  },
  res5: {
    id: 'res5',
    src: 'cinnabon.jpg',
    alt: 'Cinnabon',
    name: 'Cinnabon',
    desc: ' • Выпечка • Десерты • Капкейки',
    time: '25 - 35 Min',
    menu: [25, 26, 27, 28, 29, 30],
  },
  res6: {
    id: 'res6',
    src: 'dotdzy.jpg',
    alt: 'Точка Дзы',
    name: 'Точка Дзы — Цветной',
    desc: ' • Вьетнамская',
    time: '40 - 50 Min',
    menu: [31, 32, 33, 34, 35, 36],
  },
};
